services:
  # Frontend (Vite static site)
  - type: static
    name: iit-onboarding-web
    rootDir: apps/web
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        # After first deploy, set this to your API public URL + /api
        value: https://REPLACE_WITH_API_URL/api

  # Backend (Express, long-running web service)
  - type: web
    name: iit-onboarding-api
    env: node
    plan: free
    rootDir: apps/api
    buildCommand: npm ci
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: JWT_SECRET
        value: replace-with-a-long-random-string
      - key: WEB_ORIGIN
        # After first deploy, set this to your Web public URL
        value: https://ints-ops1.onrender.com/
