services:
  - type: static_site
    name: iit-onboarding-web
    rootDir: apps/web
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://REPLACE_WITH_API_URL/api
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate

  - type: web
    name: iit-onboarding-api
    env: node
    plan: free
    rootDir: apps/api
    buildCommand: npm ci
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: JWT_SECRET
        value: replace-with-a-long-random-string
      - key: WEB_ORIGIN
        value: https://REPLACE_WITH_WEB_URL

databases: []
